### ISSUE TITLE
Access Cycle: error on a license reading

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1056]
Customer reported a problem during license import

_Passage 1.1.2_

```
==Diagnostic==
Severe

              Error on mining conditions from file <some-personal-license-file>.licen (103: Service failed to evaluate a morsel), failure
----
org.eclipse.passage.lic.internal.api.LicensingException: Decoding error for configuration licensing.product.identifier=<some product>;licensing.product.version=<some-version>
              at org.eclipse.passage.lic.internal.bc.BcDecodedStream.produce(BcDecodedStream.java:66)
              at org.eclipse.passage.lic.internal.bc.BcStreamCodec.decode(BcStreamCodec.java:100)
              at org.eclipse.passage.lic.internal.base.conditions.mining.DecodedContent.get(DecodedContent.java:43)
              at org.eclipse.passage.lic.internal.base.conditions.mining.ArmedMiningTool.decoded(ArmedMiningTool.java:44)
              at org.eclipse.passage.lic.internal.base.conditions.mining.PersonalLicenseMiningTool.mine(PersonalLicenseMiningTool.java:57)
              at org.eclipse.passage.lic.internal.base.conditions.mining.PersonalLicenseMiningTool.lambda$0(PersonalLicenseMiningTool.java:47)
              at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
              at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
              at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
              at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
              at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
              at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
              at java.util.stream.ReferencePipeline.reduce(Unknown Source)
              at org.eclipse.passage.lic.internal.base.conditions.mining.PersonalLicenseMiningTool.mine(PersonalLicenseMiningTool.java:48)
              at org.eclipse.passage.lic.internal.base.conditions.mining.LocalConditions.all(LocalConditions.java:70)
              at org.eclipse.passage.lic.internal.base.conditions.mining.BaseLicenseReadingService.read(BaseLicenseReadingService.java:43)
              at org.eclipse.passage.lic.internal.jface.dialogs.licensing.ImportLicenseDialog.loadLicense(ImportLicenseDialog.java:144)
              at java.util.Optional.ifPresent(Unknown Source)
              at org.eclipse.passage.lic.internal.jface.dialogs.licensing.ImportLicenseDialog.browseAndLoad(ImportLicenseDialog.java:124)
              at org.eclipse.passage.lic.internal.jface.dialogs.licensing.ImportLicenseDialog.lambda$0(ImportLicenseDialog.java:82)
              at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
              at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
              at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
              at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
              at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
              at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
              at org.eclipse.jface.window.Window.open(Window.java:798)
              at org.eclipse.passage.lic.internal.jface.dialogs.licensing.GoodIntention$ImportLicense.paveTheWay(GoodIntention.java:47)
              at org.eclipse.passage.lic.internal.jface.EquinoxPassageUI.exposeAndMayBeEvenFix(EquinoxPassageUI.java:93)
              at org.eclipse.passage.lic.internal.jface.EquinoxPassageUI.investigate(EquinoxPassageUI.java:59)
              at org.eclipse.passage.lic.internal.jface.EquinoxPassageUI.acquireLicense(EquinoxPassageUI.java:42)
              at org.eclipse.passage.lic.internal.e4.ui.addons.E4LicensingAddon.applicationStarted(E4LicensingAddon.java:51)
              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
              at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
              at java.lang.reflect.Method.invoke(Unknown Source)
              at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
              at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:67)
              at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
              at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
              at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
              at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
              at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
              at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
              at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
              at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
              at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
              at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
              at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
              at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
              at <some RCP product startup point>
              at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
              at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
              at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
              at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
              at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
              at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
              at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
              at java.lang.reflect.Method.invoke(Unknown Source)
              at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
              at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
              at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: org.eclipse.passage.lic.internal.api.LicensingException: Invalid compressed data for configuration licensing.product.identifier=<some product>;licensing.product.version=<some version>
              at org.eclipse.passage.lic.internal.bc.BcDecodedStream.compressedData(BcDecodedStream.java:110)
              at org.eclipse.passage.lic.internal.bc.BcDecodedStream.produce(BcDecodedStream.java:56)
              ... 62 more
```

**Comment by eparovyshnaya** [comment]
Done by #1064: error happens when license file does not contain encrypted data (is corrupted). 

Error message is made more explanatory.
