### ISSUE TITLE
Passage Operator is broken 

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1135]
Due to `ViewersObservables` deletion from `org.eclipse.jface.databinding`, emfforms stopped handling tree-master-detail, which is the key ui solution in current version of the product. 

Thus no operation on data editing is not available. 

```
java.lang.NoClassDefFoundError: org/eclipse/jface/databinding/viewers/ViewersObservables
	at org.eclipse.emfforms.spi.swt.treemasterdetail.TreeMasterDetailComposite.renderControl(TreeMasterDetailComposite.java:200)
	at org.eclipse.emfforms.spi.swt.treemasterdetail.TreeMasterDetailComposite.<init>(TreeMasterDetailComposite.java:158)
	at org.eclipse.emfforms.spi.swt.treemasterdetail.TreeMasterDetailSWTBuilder.create(TreeMasterDetailSWTBuilder.java:367)
	at org.eclipse.passage.loc.workbench.emfforms.parts.DetailsView.createTreeMasterDetail(DetailsView.java:201)
	at org.eclipse.passage.loc.workbench.emfforms.parts.DetailsView.createRootView(DetailsView.java:176)
	at org.eclipse.passage.loc.workbench.emfforms.parts.DetailsView.show(DetailsView.java:139)
	at org.eclipse.passage.loc.users.emfforms.parts.UsersDetailsPart.showFeatureSet(UsersDetailsPart.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4031)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3636)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jface.databinding.viewers.ViewersObservables cannot be found by org.eclipse.emfforms.swt.treemasterdetail_1.26.2.20220523-0845
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:487)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 34 more
```

Though it is still possible to actually issue a license for existing data.

**Comment by ruspl-afed** [comment]
Closed with #1145
