### ISSUE TITLE
Operator distributive configuration issue makes it fail on startup

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1370]
Passage Operator fails on startup

```
Failed to configure logging
java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because the return value of "org.eclipse.core.runtime.FileLocator.find(org.osgi.framework.Bundle, org.eclipse.core.runtime.IPath, java.util.Map)" is null
        at org.eclipse.passage.lic.equinox.io.FileFromBundle.get(FileFromBundle.java:41)
        at org.eclipse.passage.loc.operator.seal.OperatorFramework.logConfig(OperatorFramework.java:70)
        at org.eclipse.passage.lic.internal.execute.Logging.configure(Logging.java:27)
        at org.eclipse.passage.loc.operator.seal.OperatorFramework.configureLogging(OperatorFramework.java:65)
        at org.eclipse.passage.loc.operator.seal.OperatorFramework.<init>(OperatorFramework.java:41)
        at org.eclipse.passage.loc.operator.seal.OperatorFramework.<clinit>(OperatorFramework.java:35)
        at org.eclipse.passage.loc.operator.seal.OperatorFrameworkSupplier.get(OperatorFrameworkSupplier.java:26)
        at org.eclipse.passage.loc.operator.seal.OperatorFrameworkSupplier.get(OperatorFrameworkSupplier.java:1)
        at java.base/java.util.Optional.flatMap(Optional.java:289)
        at org.eclipse.passage.lic.equinox.EquinoxFrameworkAware.lambda$6(EquinoxFrameworkAware.java:77)
        at org.eclipse.passage.lic.equinox.EquinoxFrameworkAware.withReference(EquinoxFrameworkAware.java:123)
        at org.eclipse.passage.lic.equinox.EquinoxFrameworkAware.withFramework(EquinoxFrameworkAware.java:74)
        at org.eclipse.passage.lic.e4.ui.addons.E4LicensingAddon.product(E4LicensingAddon.java:70)
        at org.eclipse.passage.lic.e4.ui.addons.E4LicensingAddon.applicationStarted(E4LicensingAddon.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Comment by eparovyshnaya** [comment]
Fixed with #1377
