### ISSUE TITLE
`lic.bc.tests.StreamEncodingTest` fails stochastically

### ISSUE THREAD

**Issue by zelenyhleb** [eclipse-passage/passage#1471]
Test failure seems unrelated when first [appeared](https://ci.eclipse.org/passage/job/eclipse-passage/job/passage/job/PR-1470/3/testReport/junit/org.eclipse.passage.lic.internal.bc.tests/StreamEncodingTest/properKeyIsRequired/), but it may indicate some hidden problems, hence needs to be investigated and made stable.

`properKeyIsRequired`
```
java.lang.ClassCastException: class org.bouncycastle.bcpg.TrustPacket cannot be cast to class org.bouncycastle.bcpg.UnknownPacket (org.bouncycastle.bcpg.TrustPacket and org.bouncycastle.bcpg.UnknownPacket are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @291cbe70)
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at org.bouncycastle.openpgp.PGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.bouncycastle.openpgp.jcajce.JcaPGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.eclipse.passage.lic.bc.BcResidentSecretKey.rings(BcResidentSecretKey.java:60)
```

**Comment by eparovyshnaya** [comment]
same test occasionaly also fails with the following trace:
```
org.bouncycastle.bcpg.UnsupportedPacketVersionException: Unsupported Public Key Packet version encountered: 229
	at org.bouncycastle.bcpg.PublicKeyPacket.<init>(Unknown Source)
	at org.bouncycastle.bcpg.PublicKeyPacket.<init>(Unknown Source)
	at org.bouncycastle.bcpg.SecretKeyPacket.<init>(Unknown Source)
	at org.bouncycastle.bcpg.SecretKeyPacket.<init>(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.readPacket(Unknown Source)
	at org.bouncycastle.openpgp.PGPSecretKeyRing.<init>(Unknown Source)
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at org.bouncycastle.openpgp.PGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.bouncycastle.openpgp.jcajce.JcaPGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.eclipse.passage.lic.bc.BcResidentSecretKey.rings(BcResidentSecretKey.java:60)
	at org.eclipse.passage.lic.bc.BcResidentSecretKey.get(BcResidentSecretKey.java:48)
	at org.eclipse.passage.lic.bc.BcStreamCodec.encode(BcStreamCodec.java:91)
	at org.eclipse.passage.lic.internal.bc.tests.StreamEncodingTest.properKeyIsRequired(StreamEncodingTest.java:77)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:140)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.start(HeadlessTestApplication.java:29)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:219)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:149)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:115)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:467)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:298)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:627)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1431)
	at org.eclipse.equinox.launcher.Main.main(Main.java:[1403](https://github.com/eclipse-passage/passage/actions/runs/15945386429/job/44978772120#step:5:1404))
```

**Comment by eparovyshnaya** [comment]
same test

```
Errors: 
  StreamEncodingTest.properKeyIsRequired:75 » ClassCast class org.bouncycastle.bcpg.UserIDPacket cannot be cast to class org.bouncycastle.bcpg.UnknownPacket (org.bouncycastle.bcpg.UserIDPacket and org.bouncycastle.bcpg.UnknownPacket are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7e70bd39)
```

**Comment by eparovyshnaya** [comment]
#1543
