### ISSUE TITLE
2.0.0 release fails on startup

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#997]
Download [2.0.0 FLS release distributive for Windows](https://download.eclipse.org/passage/downloads/release/2.0.0/fls/), run 'PassageServer.exe'

Console opens and there 'unresolved requirement' complain appears. It does not prevent the server from starting though.

============================================

org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ecf.provider.filetransfer.httpclient45.win32 [49]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=win32)"
  Unresolved requirement: Import-Package: org.apache.http.impl.auth.win; version="[4.5.0,5.0.0)"
    -> Export-Package: org.apache.http.impl.auth.win; bundle-symbolic-name="org.apache.httpcomponents.httpclient.win"; bundle-version="4.5.13.v20210128-2225"; version="4.5.13"; x-internal:="true"; uses:="org.apache.http,org.apache.http.auth,org.apache.http.client,org.apache.http.impl.auth,org.apache.http.protocol,org.apache.http.util"
       org.apache.httpcomponents.httpclient.win [21]
         Unresolved requirement: Require-Capability: eclipse.platform; filter:="(osgi.os=win32)"

        at org.eclipse.osgi.container.Module.start(Module.java:463)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1849)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1842)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1783)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1747)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1669)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
==============================================

Ported
---
from [bugs.eclipse.org: 574492](https://bugs.eclipse.org/bugs/show_bug.cgi?574492)
Version: 2.0.1

**Comment by ruspl-afed** [comment]
Not repeatable with 2.5.0 RC1
